baseURL = "https://lommel.lukin.be/"
languageCode = "nl-BE"
title = "Covid Vaccinaties Lommel"
googleAnalytics = "UA-24094817-11"

[Author]
  name = "Maarten Huijsmans"
  email = "maarten@lukin.be"

[params]
  description = "Dagelijkse update over de vaccinatie cijfers in Lommel."
