baseURL = "https://vaccinaties.lukin.be/"
languageCode = "nl-BE"
title = "Vaccinatieteller per gemeente"
googleAnalytics = "UA-24094817-11"

[Author]
  name = "Maarten Huijsmans"
  email = "maarten@lukin.be"

[params]
  description = "Vaccinatieteller: dagelijkse update over de vaccinatie cijfers in jouw gemeente."
  suggestedMax = 50
